### PR TITLE
Support private assets and enhance security

### PR DESCRIPTION
**Pull request by aerni**
This PR adds support for [Private Containers](https://statamic.dev/assets/#private-containers) and enhances security by encrypting the files array in the URL. It also adds support to zipping files from absolute paths along with the support of zipping files by URL.

### CODE REVIEW

**Comment by aerni** [comment]
I came across some issues with files on S3. I will have to do some major refactoring to properly support S3. As of now, this PR breaks S3. And I also noticed that the caching feature never worked when using an S3 disk as well. So this will all be cleaned up in the next release.

**Comment by aerni** [comment]
Everything should be fixed now. Support was added for public and private assets both locally and on S3. It also adds the ability to cache zips on S3 as well.

**Comment by michaelr0** [comment]
Due do some oddities in the naming of the Flysystem S3 Adapter, https://github.com/aerni/statamic-zipper/blob/feature/security/src/Zipper.php#L53 might need to also check for `AwsS3V3Adapter`

And because it is never just 'that easy' `->getBucket()` and `->getClient()` arent methods that are available on `League\Flysystem\AwsS3V3\AwsS3V3Adapter`

Although, this appears to be working for me with `Illuminate\Filesystem\AwsS3V3Adapter` and Laravel 9

```php
use Illuminate\Filesystem\AwsS3V3Adapter;
use League\Flysystem\AwsS3v3\AwsS3Adapter;

protected static function addFile(Asset|string $file, ZipStream $zip): ZipStream
{
    if (is_string($file)) {
        return $zip->add($file);
    }

    $filesystem = $file->disk()->filesystem();
    $adapter = $filesystem->getAdapter();

    if ($adapter instanceof Local) {
        return $zip->add($file->resolvedPath());
    }

    if ($adapter instanceof AwsS3Adapter) {
        $path = "s3://{$adapter->getBucket()}/{$file->path}";
        $s3Client = $adapter->getClient();
        $file = File::make($path)->setS3Client($s3Client);

        return $zip->add($file);
    }

    if ($filesystem instanceof AwsS3V3Adapter) {
        $path = "s3://{$filesystem->getConfig()['bucket']}/{$file->path}";
        $s3Client = $filesystem->getClient();
        $file = File::make($path)->setS3Client($s3Client);

        return $zip->add($file);
    }

    throw new Exception('Zipper doesn\'t support ['.$adapter::class.'].');
}
```

**Comment by aerni** [comment]
Thanks a lot! Supporting both Laravel 8 and 9 is tricky. I'll be dropping Laravel 8 with the next release.

**Comment by aerni** [comment]
@michaelr0 Can you give this another go with your S3 setup? Both with and without the Zipper caching option enabled. I tested it on my side of things. But two set of eyes are always better.

**Comment by michaelr0** [comment]
@aerni all good on this end

**Pull request merged**
