### PR TITLE
Link Expiry

### LINKED ISSUE #9: Add expiry to links generated by zipper action
Either public or private assets, the zip action URL will always continue to create the zip file which is not idea behavior for certain use-cases involving digital download deliveries or one-time content downloads

### PR DESCRIPTION
**Pull request by aerni**
This PR closes #9 by providing the option to set an expiration time for links. You can globally set the expiry in the config or set it on a link. 

Expire the link after 10 minutes:
```antlers
{{ zip:images expiry="10" }}
```

### CODE REVIEW

**Comment by ghost** [comment]
**config/zipper.php**

Instructions say to set minutes here but this i think makes more sense as a boolean field that should be true or false and left to the antlers tag to discern time.

With config set to null, links never expire. With config set to 1 - links expire in one minute, and with config set to true and {{ expiry="1" }} links expire in one minute.

This however does not rename the next action link - so if you want to re use the same download button for a second user, the link expiry is across the entire system - link expiry plus renaming the next action URL is the intended use case for our system.

**Comment by ghost** [comment]
Actually, with a combination of adding a datetime-string to the download filename, and the link expiry, i think this will now work as we want it to!

thank you!

**Comment by aerni** [comment]
You don't have to use the `expiry` in the config if you don't want to. Just leave it at `null` or `0` and use the `expiry` on the tag. The config option is simply there to provide a global expiry in case someone wants this.

I don't understand what you mean by "This however does not rename the next action link". The link changes on every reload of the page. That's how the underlying cipher works. So you should have unique links on every reload. And the way link expiration works is by using Laravel's signed routes. The `signature` in each link will be checked, and if it is expired, it will throw an error.

**Comment by ghost** [comment]
i must have been confused and misunderstood the code/ docs - but its not an issue since the change actually does work as intended. Disregard former comment

**Pull request merged**
