### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by aerni**
This PR includes a comprehensive refactor of the codebase. It also introduces a new `route` method on the `Aerni\Zipper\Zipper` class which makes it possible to use this addon programmatically without using the Antlers tag.

This should also make the request of PR https://github.com/aerni/statamic-zipper/pull/4 possible.

### CODE REVIEW

**Comment by michaelr0** [comment]
Hi @aerni,

Thanks, I have been able to test this and have the following feedback.

https://github.com/aerni/statamic-zipper/blob/feature/refactor/src/Zipper.php#L46 Blocks CDN or Cloud storage from being a possibility (S3 etc)

And https://github.com/aerni/statamic-zipper/blob/feature/refactor/src/Zipper.php#L42 has substr with an offset of 1, this would cause the `h` from `http://` or `https://` to be dropped on fully qualified urls (such as with S3)

Removing those, seems to work for us.
```php
    protected static function files(Collection|array $files): array
    {
        return collect($files)
            ->map(fn ($file) => match (true) {
                ($file instanceof Asset) => $file->url(),
                (is_array($file)) => Arr::get($file, 'url'),
                default => $file,
            })
            ->all();
    }
```

**Comment by aerni** [comment]
Oh, good catch! Both issues should be fixed now. Can you give it another try?

**Comment by michaelr0** [comment]
Hi @aerni,

I can confirm that it works, The use of the `Http::get` check might introduce some slowness for generating downloads which have a number of files within them, but at that point, it is probably worth setting the Zipper config to ` 'save' => true,`

**Comment by aerni** [comment]
Cool, thanks for checking. 

I wasn't sure if I should add `Http::get` or not. This is a new addition that wasn't there before. I've added it to avoid an exception if a requested file doesn't exist. This could be the case when creating a zip with files from an external source. 

The HTTP request happens before `'save' => true` though. But I could probably refactor this.

What is your opinion? Should I remove it or not? It's really only there to avoid a potential exception.

**Comment by michaelr0** [comment]
I'd probably suggest removing it, and having the check in place on the actual download generation action, rather than the link creation action.

**Comment by aerni** [comment]
I'm already working on exactly that ;-)

**Comment by aerni** [comment]
Ok, this should be all good now. The HTTP request now only happens when the zip is created. And the response is cached for 60 minutes.

Want to do one last check if that works for you? Then I'll merge and release.

**Comment by michaelr0** [comment]
Yep, looks good to me.

**Pull request merged**
